# Generated by Django 5.2.3 on 2025-07-14 23:54

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardfileuser',
            name='status',
            field=models.CharField(max_length=20, choices=[('not-viewed', 'Not Viewed'), ('viewed', 'Viewed')], default='not-viewed'),
        ),
    ]
