# Generated by Django 5.2.3 on 2025-07-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_file_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='file',
            name='status',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='upload_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
