# Generated by Django 5.2.3 on 2025-07-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_file_profiles_remove_file_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path',
        ),
    ]
