# Generated by Django 5.2.3 on 2025-07-24 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_make_superuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Name of the uploaded file', max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded')),
                ('user', models.ForeignKey(help_text='The user who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'db_table': 'dashboard_uploaded_files',
                'ordering': ['-upload_date'],
            },
        ),
    ]
