# Generated by Django 5.2.3 on 2025-07-08 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardFileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.file')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
            options={
                'db_table': 'dashboard_file_user',
                'unique_together': {('file', 'user_profile')},
            },
        ),
    ]
