# Generated by Django 5.2.3 on 2025-07-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dashboardfileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardfileuser',
            name='status',
            field=models.CharField(choices=[('not-viewed', 'Not Viewed'), ('viewed', 'Viewed')], default='not-viewed', max_length=20),
        ),
    ]
