# Generated by Django 5.2.3 on 2025-07-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(blank=True, help_text='Relative path to the uploaded file', max_length=500, null=True),
        ),
    ]
