# Generated by Django 5.2.3 on 2025-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_uploadedfile_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_content',
            field=models.BinaryField(blank=True, help_text='The actual content of the uploaded file', null=True),
        ),
    ]
